# Generated by Django 3.1.2 on 2020-10-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_yarns', '0001_initial'),
        ('api_time_set', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesetmodels',
            name='belongs_yarn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_yarns.yarnsmodels'),
        ),
    ]
