version: '3.7'

services:
  backend:
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PW
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33068:3306