# Generated by Django 3.1.2 on 2020-10-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_bookings', '0001_initial'),
        ('api_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodels',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_fields.fieldsmodels'),
        ),
    ]
