# Generated by Django 3.1.3 on 2021-02-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yarns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarnsmodels',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='yarnsmodels',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
